"""create tables

Revision ID: d0dabe4f8660
Revises: 
Create Date: 2022-06-07 20:51:12.246313

"""
from dataclasses import replace
from alembic import op
import sqlalchemy as sa
from sql_app.security import get_password_hash


# revision identifiers, used by Alembic.
revision = 'd0dabe4f8660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_admin = false")
    # hashed_password = op.execute("SELECT hashed_password FROM users WHERE hashed_password LIKE '%notreallyhashed'")
    con = op.get_bind()
    users = con.execute("SELECT * FROM users WHERE hashed_password LIKE '%notreallyhashed'")
    for user in users:
        password = user.hashed_password.replace("notreallyhashed", "")
        hashed_password = get_password_hash(password)
        con.execute("UPDATE users SET hashed_password = '" + hashed_password +
                    "' WHERE id = " + str(user.id))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
