"""add is admin from user

Revision ID: f1e224b81bca
Revises: f26934ba58c8
Create Date: 2022-07-24 19:25:18.566312

"""
from alembic import op
import sqlalchemy as sa
from sql_app.security import get_password_hash


# revision identifiers, used by Alembic.
revision = 'f1e224b81bca'
down_revision = 'f26934ba58c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_admin = false")
    con = op.get_bind()
    users = con.execute("SELECT * FROM users WHERE hashed_password LIKE '%notreallyhashed'")
    for user in users:
        password = user.hashed_password.replace("notreallyhashed", "")
        hashed_password = get_password_hash(password)
        con.execute("UPDATE users SET hashed_password = '" + hashed_password +
                    "' WHERE id = " + str(user.id))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
